apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-6mzv
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0004-tenant/tkrw-pr712-0075-0004-app/devfile-sample-6mzv@sha256:bd4c08ef6897afbae1aff5c5070eab8cc94cdea4b6716283ccfdd6624a4444ec
        name: my-nodejs
        resources: {}
status: {}
